name: Deploy to Railway

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          cd backend
          npm install
          
      - name: Build
        run: |
          cd backend
          npm run build
          
      - name: Deploy to Railway
        uses: railwayapp/action@v1
        with:
          service: studio-in-cloud-scheduler
          environment: production
          token: ${{ secrets.RAILWAY_TOKEN }} 